export const BACKOFFICE_INVENTORY_TYPES = {
    CHANGE_PRODUCT_VALUE :"CHANGE_PRODUCT_VALUE",
    CHANGE_CATEGORY_VALUE :"CHANGE_CATEGORY_VALUE",
    CREATE_NEW_CATEGORY : "CREATE_NEW_CATEGORY",
    FILTERED: "FILTERED",
    // FILTER_BY_CATEGORY : "FILTER_BY_CATEGORY"

    //API

    READ_ALL_DATA: "READ_ALL_DATA"

    //END
}