export const BACKOFFICE_TURN_TYPES = {
    SET_EDITABLE_CHAIR : "SET_EDITABLE_CHAIR",
    SET_EDITABLE_DAY: "SET_EDITABLE_DAY",
    LOAD_DATA : "LOAD_DATA",
    ADD_COUNT : "ADD_COUNT",
    REST_COUNT : "REST_COUNT",
    GET_DAY_INITAL_COUNT : "GET_DAY_INITAL_COUNT",
}