export const BACKOFFICE_TURN_DASHBOARD_TYPES  = {
    RESET_INITIAL_STATE :"RESET_INITIAL_STATE",
    // GET_TODAYS_SCHEDULE :"GET_TODAYS_SCHEDULE",
    // GET_TOMOORROW_SCHEDULE : "GET_TOMOORROW_SCHEDULE",
    SET_DATE :"SET_DATE",
    FILTER_DASHBOARD : "FILTER_DASHBOARD",
    EDITE_TURN_SCHEDULE : "EDITE_TURN_SCHEDULE",
    ORDER_BY_DATE: "ORDER_BY_DATE",
    SET_TURN_STATUS : "SET_TURN_STATUS",

    //API ACTIONS 

    READ_ALL_ORDERTURN : "READ_ALL_ORDERTURN"

    //END
}
