export const BACKOFFICE_TURN_TYPES = {
    SET_EDITABLE_CHAIR : "SET_EDITABLE_CHAIR",
    SET_EDITABLE_DAY: "SET_EDITABLE_DAY",
    LOAD_DATA : "LOAD_DATA",
    ADD_COUNT : "ADD_COUNT",
    REST_COUNT : "REST_COUNT",
    GET_DAY_INITAL_COUNT : "GET_DAY_INITAL_COUNT",
    SAVE_CHAIR_SCHEDULE : "SAVE_CHAIR_SCHEDULE",
    SET_START_HOUR : "SET_START_HOUR",
    SET_END_HOUR :"SET_END_HOUR",
    SET_CHAIR_NAME :"SET_CHAIR_NAME",
    SWITCH_CHAIR_STATUS :"SWITCH_CHAIR_STATUS",
    SWITCH_DAY_STATUS: "SWITCH_DAY_STATUS",
}