export const TYPES ={
    ADD_TO_CART:"ADD_TO_CART",
    ADD_ONE_TO_CART:"ADD_ONE_TO_CART",
    REMOVE_ONE_FROM_CART:"REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
    CLEAN_CART:"CLEAN_CART",
    LOAD_DATA:"LOAD_DATA",

    //ACTIONS API ITEM

    READ_ALL_DATA:"READ_ALL_DATA"
    // INCREMENT:"INCREMENT",
    // DECREMENT:"DECREMENT",
}

